@Blog_HostAddress = http://localhost:5118

GET {{Blog_HostAddress}}/api/post/

###
GET {{Blog_HostAddress}}/api/user/1

###
GET {{Blog_HostAddress}}/api/user/

###
POST {{Blog_HostAddress}}/api/user/create/ HTTP/1.1
content-Type: application/json

{
    "email": "user@email.com",
    "username": "user1",
    "password": "password",
    "fullName": "Amaechi Jude"
}

###
GET {{Blog_HostAddress}}/api/post/
###

POST {{Blog_HostAddress}}/api/post/create/ HTTP/1.1
content-Type: application/json

{
    "title": "Post two",
    "content": "Post two content",
    "userId": 1
}
