
services:
  blogapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: blogapp
    volumes:
      - ./Uploads:/app/Uploads
      - ./Uploads:/src/Uploads
    # ports:
    #   - "8080:8080"
    #   - "8081:8081"
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - blogapp


